Damon develop
pmartR/malbacR pull request #3
Opened 2023-09-12 15:00 UTC by leac176

Updated bc_power, bc_nomis, bc_qcrlsc, and bc_serrf to account for the fact that they all do not handle normalization without a backtransform due to negative values (Power, NOMIS, and SERRF) or values that are equal to 0 (QC-RLSC)

2023-12-15 01:26 UTC, evanglass commented on DESCRIPTION
> +URL: https://pmartr.github.io/malbacR/
Minor nitpick: is there a reason this is down here? It seems more common for URL to go between Description and License

2023-12-15 01:26 UTC, evanglass commented on R/bc_eigenMS.R
> +  # }
Is there a reason this wasn't removed entirely instead of commented out? (Also lines 128-136)

2023-12-15 01:26 UTC, evanglass commented on R/bc_qcrfsc.R
> +    set.seed(2023)
I know the seed is set in a bunch of different places that aren't even in this PR, but ideally the original seed should be restored when the function exits to avoid breaking any potential package user's code.

Something like
`old_seed <- .Random.seed`
`on.exit(.Random.seed <- old_seed)`

or even simpler (with an extra package import)
`withr::with_seed({ ...Code which uses set seed... })`

2023-12-15 01:26 UTC, evanglass commented on R/bc_serrf.R
>          predictor_vars = paste0("var",seq(from = 1, to = length(colnames(norm_dat)[sel_var]),by = 1))
I seem to be getting failures with this dopar loop. I'm not entirely sure why (maybe a Windows thing). Only thing that has seemed to fix it is replacing line 238 with:
```
# Set up cluster with required variables
cl <- parallel::makeCluster(parallel::detectCores()-1)
on.exit(parallel::stopCluster(cl))
doParallel::registerDoParallel(cl)
parallel::clusterExport(cl, 
                        c("batch_info", "batchName", "corrs_train",
                        "corrs_target", "training_dat", "testing_dat"),
                        envir = environment())
```

2023-12-15 01:26 UTC, evanglass commented on R/impute.R
> +    stop ("Imputation is recommended on data that is on log2 scale. Please transform your data to be log2.")
The wording of this message is a bit weird. Is imputation only recommended for _all_ data which is on a log2 scale, or is it just recommended that data be on a log2 scale for imputation? And is it a recommendation or a requirement (since it does stop the function)?

2023-12-15 01:26 UTC, evanglass commented on R/internal_tiger.R
> +  # borrowed from caret::createFolds()
**This might cause a software license issue** since caret package is GPL. Probably best to check with someone who knows more about this stuff than me.

2023-12-15 01:26 UTC, evanglass commented on R/internal_tiger.R
> +Internal.boxplot.stats <- function(x, # borrowed from grDevices::boxplot.stats()
R core packages like grDevices are under GPL. Probably best to double check with somebody who knows how to deal with licenses and stuff.

2023-12-15 01:26 UTC, evanglass commented on tests/testthat/test_bc_qcrfsc.R
> +  mdata <- group_designation(mdata,main_effects = "Age")
Missing pmartR::
```suggestion
  mdata <- pmartR::group_designation(mdata,main_effects = "Age")
```

2023-12-15 01:26 UTC, evanglass commented on R/bc_qcrfsc.R
> +    id_col <- which(names(orig_edata) == get_edata_cname(omicsData))
Missing pmartR::
```suggestion
    id_col <- which(names(orig_edata) == pmartR::get_edata_cname(omicsData))
```

2023-12-15 14:11 UTC, leac176 commented on DESCRIPTION
> +URL: https://pmartr.github.io/malbacR/
I think that just got tacked on at the end automatically once I created the webpage for malbacR using devtools as that occurred as one of the last updates. I can place it elsewhere if that makes more sense though

2023-12-15 14:13 UTC, leac176 commented on R/bc_eigenMS.R
> +  # }
Not really, initially this was used to let users include emeta information to inform some scaling via this method but it showed negligible and became clear that if we were to go that route, we would need a bit more quality control in the background to deal with the structure of columns within emeta

2023-12-15 14:31 UTC, leac176 commented on R/internal_tiger.R
> +  # borrowed from caret::createFolds()
Good point - we originally just used the TIGER package but some internal stuff were not working so I had to draw from their internal functions which then use Caret and GPL so this is a good question. I might be able to just use Caret and GPL directly perhaps?

2023-12-15 14:31 UTC, leac176 commented on R/internal_tiger.R
> +Internal.boxplot.stats <- function(x, # borrowed from grDevices::boxplot.stats()
Same as before, I will look into that

2023-12-15 14:40 UTC, leac176 commented on R/impute.R
> +    stop ("Imputation is recommended on data that is on log2 scale. Please transform your data to be log2.")
We only want to impute on log2 scale. I make the wording more clear. Thanks!

2023-12-15 14:46 UTC, leac176 commented on R/bc_qcrfsc.R
> +    set.seed(2023)
Thanks! I will add that code where seeds are being used across the package.

2023-12-18 17:27 UTC, evanglass commented on R/internal_tiger.R
> +  # borrowed from caret::createFolds()
Sorry if I wasn't clear, GPL is a software license: https://cran.r-project.org/web/licenses/GPL-2

2023-12-21 00:58 UTC, evanglass requested changes
Sorry, I missed a few more missing pmartR:: prefixes

2023-12-21 00:58 UTC, evanglass commented on tests/testthat/test_bc_qcrfsc.R
> +  mdata <- applyFilt(molfilt,mdata)
```suggestion
  molfilt <- pmartR::molecule_filter(mdata,use_groups = TRUE)
  mdata <- pmartR::applyFilt(molfilt,mdata)
```

2023-12-21 00:58 UTC, evanglass commented on tests/testthat/test_bc_qcrfsc.R
> +  udn_with_emet <- applyFilt(molfilt,udn_with_emet)
```suggestion
  udn_with_emet <- pmartR::group_designation(udn_with_emet,main_effects = "Age")
  molfilt <- pmartR::molecule_filter(udn_with_emet,use_groups = TRUE)
  udn_with_emet <- pmartR::applyFilt(molfilt,udn_with_emet)
```

2023-12-21 00:58 UTC, evanglass commented on tests/testthat/test_loglik.R
> +  mdata <- applyFilt(molfilt,mdata)
```suggestion
  molfilt <- pmartR::molecule_filter(mdata)
  mdata <- pmartR::applyFilt(molfilt,mdata)
```

2023-12-21 00:58 UTC, evanglass commented on tests/testthat/test_opt.R
> +  mdata <- applyFilt(molfilt,mdata)
```suggestion
  molfilt <- pmartR::molecule_filter(mdata)
  mdata <- pmartR::applyFilt(molfilt,mdata)
```

2023-12-21 21:40 UTC, evanglass commented on vignettes/malbacR_vignette_condensed_filtered.Rmd
>                           alpha = 0, cutoff = 0.1, K = 10)
The parameter names got updated, but weren't changed here
```suggestion
amide_wave <- bc_waveica(omicsData = pmart_amideFilt, injection_cname = "Injection_order",
                         version = "WaveICA2.0", alpha = 0, cutoff_injection = 0.1, K = 10)
```

2023-12-21 22:46 UTC, evanglass commented on R/impute.R
> +#' pmart_amide <- edata_transform(pmart_amide,"log2")
```suggestion
#' library(pmartR)
#' pmart_amide <- edata_transform(pmart_amide,"log2")
```

2023-12-21 22:46 UTC, evanglass commented on R/impute.R
> +#' pmart_amide <- edata_transform(pmart_amide,"log2")
```suggestion
#' library(pmartR)
#' pmart_amide <- edata_transform(pmart_amide,"log2")
```

2023-12-22 23:46 UTC, evanglass commented
Is there a reason `amide_eigen` isn't plotted in the vignettes?

2023-12-23 00:18 UTC, evanglass commented on vignettes/malbacR_vignette_condensed_filtered.Rmd
>                           alpha = 0, cutoff = 0.1, K = 10)
This also applies to the extended vignette as well, and the description paragraph will need to be modified as well.

2024-01-05 22:15 UTC, evanglass approved these changes
Looks good

2024-01-16 19:55 UTC, merged